### PR TITLE
Add new Wikidata properties

### PR DESCRIPTION
**Pull request by jc86035**
I've added the two newest MusicBrainz properties. I don't know what the tuples are so I haven't added those.

### CODE REVIEW

**Comment by mineo** [comment]
This looks good, but will not work without the IDs for the [link_type](https://wiki.musicbrainz.org/MusicBrainz_Database/Schema#link_type.2C_link_attribute_type.2C_.26_link_type_attribute_type_tables) table, since they're used to retrieve the links from the database. I'm afraid I don't know where one can find the IDs without an MB database :-(

**Comment by mineo** [comment]
In addition to the previous comment, merging this will make the bot automatically start adding them on wikidata. Before that, adding both of those MBID types automatically should be approved.

**Comment by jc86035** [comment]
Actually, I just realized that since MusicBrainz doesn't yet support Wikidata links for releases or recordings, it wouldn't be useful to add them to the bot code since there wouldn't be any links to add. It would be more useful to do this when Wikidata links are enabled for those two entity types, which would presumably only happen once there are enough Wikidata items for releases and recordings for enabling links to be useful.

**Comment by mineo** [comment]
Let's close this for now. It's unlikely we'll be able to move forward with this PR in the near future.

**Pull request closed without merging**
